config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get"about" => "pages#about" #creates about_path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	
	#creates two versions of image
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
      # Include default devise modules. Others available are:
      # :token_authenticatable, :confirmable,
      # :lockable, :timeoutable and :omniauthable
      devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable

      has_many :pins, dependent: :destroy

      validates :name, presence: true
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  #user must be signed in before creating a new pin
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    if user_signed_in?
    @pins = Pin.all.order('created_at DESC').limit(500).paginate(:page => params[:page], :per_page => 100)
    else
     @pins = Pin.all.sample(52)
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build #devise helper to build pin through the user model


  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinspiration", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <ul class="nav navbar-nav navbar-right">


        <% if user_signed_in? %>

          <li> <%= link_to raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Pin'), new_pin_path, id: 'new-pin' %> </li>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
         

          
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
           <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinspiration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	
	<%= render 'layouts/header' %>
	
		<% flash.each do |name, msg| %>
		<div class="container">
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		</div>
		<%= yield %>
	
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center" style="width:100%">

         <h1>Welcome to Pinspiration!</h1>
         <h3> A place of pins and inspiration </h3>
         <br/>
          
         <p>
           <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
           <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
           
      </p>    
    </div>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1>About us</h1>
<p>We are working on out Pinteresting app!</p>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
         <h1>Welcome to my app!</h1>

          <% if user_signed_in? %>
          		#do something
          <% else %>
         <p>
           <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
           <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
           <%end%>
      </p>    
    </div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>
<div class="container">
<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>


    <div class="row"> <!-- Give this div your desired background color -->
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    
                </div>
            </div>
        </div>
    </div>
</div>

 <div id="pins" class="transitions-enabled">
      <% @pins.each do |pin| %>
        <div class="box panel panel-default" style="margin-left:10px">
    
          <%= link_to image_tag(pin.image.url(:medium)), pin %>
          <div class="panel-body">
            <p><%= pin.description %></p>
           <strong> <%= pin.user.name if pin.user %> </strong>
            
            <% if  current_user && pin.user == current_user %>
            <div class="actions">
              <%= link_to raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit'), edit_pin_path(pin) %> |
              <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete'), pin, method: :delete, data: { confirm: 'Are you sure?' } %>
               </div>
            <% end %>

          </div>
        </div>
      <% end %>
    </div>

    <% if user_signed_in? %>
    <div class="center">
    <%= will_paginate @pins, renderer: BootstrapPagination::Rails%>
    </div>
    <% else %>
    <div class="center">
    <h3 style="color:#c0392b"> Please <%= link_to "log in", new_user_session_path, :style=>'text-decoration: underline;' %> to view all pins</h3>
    </div>
    <%end%>

app/views/pins/new.html.erb
<div class="container">
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<div class="container">

<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
		<div class="panel-body">
		<p><%= @pin.description %></p>
		<p><strong> <%= @pin.user.name if @pin.user %> </strong></p>

		<% if @pin.user == current_user %>
		<%= link_to raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit'), edit_pin_path(@pin) %> |
              <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete'), @pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>

		</div>

	</div>

</div>
</div>